package com.maku.myfitness.core.util

class ConstantString {

    val PREF_LAST_UN_COMPLETE_DAY = "PREF_LAST_UN_COMPLETE_DAY"

    val FB_BANNER_TYPE_AD = "FB_BANNER_TYPE_AD"
    val FB_RECTANGLE_BANNER_TYPE_AD = "FB_RECTANGLE_BANNER_TYPE_AD"
    val GOOGLE_BANNER_TYPE_AD = "GOOGLE_BANNER_TYPE_AD"
    val GOOGLE_RECTANGLE_BANNER_TYPE_AD = "GOOGLE_RECTANGLE_BANNER_TYPE_AD"

    val AD_TYPE_FB_GOOGLE = "AD_TYPE_FB_GOOGLE"
    val FIRST_TIME_OPEN = "FIRST_TIME_OPEN"
    val GOOGLE_BANNER = "GOOGLE_BANNER"
    val GOOGLE_INTERSTITIAL = "GOOGLE_INTERSTITIAL"
    val GOOGLE_REWARDED_VIDEO = "GOOGLE_REWARDED_VIDEO"
    val FB_BANNER = "FB_BANNER"
    val FB_BANNER_RECTANGLE_AD = "FB_BANNER_RECTANGLE_AD"
    val FB_INTERSTITIAL = "FB_INTERSTITIAL"
    val FB_REWARDED_VIDEO = "FB_REWARDED_VIDEO"
    val FIRST_CLICK_COUNT = "FIRST_CLICK_COUNT"
    val EXTRA_REMINDER_ID = "Reminder_ID"
    val WEIGHT_TABLE_DATE_FORMAT = "yyyy-MM-dd"
    val SPLASH_SCREEN_COUNT = "splash_screen_count"
    val START_BTN_COUNT = "start_btn_count"
    val EXIT_BTN_COUNT = "exit_btn_count"
    val STATUS_ENABLE_DISABLE = "STATUS_ENABLE_DISABLE"
    val AD_TYPE = "AD_TYPE"


    val GOOGLE_ADMOB_APP_ID = "ca-app-pub-3940256099942544~3347511713"
    val GOOGLE_BANNER_ID = "ca-app-pub-3940256099942544/6300978111"
    val GOOGLE_INTERSTITIAL_ID = "ca-app-pub-3940256099942544/1033173712"


    val FB_BANNER_ID = "IMG_16_9_APP_INSTALL#YOUR_PLACEMENT_ID"
    val FB_INTERSTITIAL_ID = "IMG_16_9_APP_INSTALL#YOUR_PLACEMENT_ID"


    val AD_FACEBOOK = "facebook"
    val AD_GOOGLE = "google"
    val AD_TYPE_FACEBOOK_GOOGLE = AD_GOOGLE


    val ENABLE = "Enable"
    val DISABLE = "Disable"
    val ENABLE_DISABLE = ENABLE

}